#pragma once

#include <regex>

#include "base/lockable.hpp"

namespace beast_router {

/// Provides the sequential routing functionality.
/**
 * The common class which provides the basic routing features 
 * e.g. get(), put(), post() and delete_() handling.<br>
 * By using RegExp it stores and maps the corresponding executors 
 * given by invoking the respective attached methods.
 *
 * ### Example
 * ```cpp
 * #include "beast_router.hpp"
 * ...
 * auto clb = [](const beast_http_request &rq, http_context &ctx, const std::smatch &match) {
 *      beast_string_response rp{boost::beast::http::status::ok, rq.version()};
 *      rp.set(boost::beast::http::field::content_type, "text/html");
 *
 *      std::stringstream i_str;
 *      i_str << 
 *          "Generated by the thread: " << std::this_thread::get_id();
 *
 *      rp.body() = i_str.str();
 *
 *      rp.prepare_payload();
 *      rp.keep_alive(rq.keep_alive());
 *      ctx.send(rp);
 * }
 *
 * g_router.get(R"(^/.*$)", std::move(clb));
 * ```
 */
template<class Session>
class router
{
public:
    /// Typedef referencing to self
    using self_type = router<Session>;

    /// Typedef referencing to Session
    using session_type = Session;

    /// Typedef referencing to mutex
    using mutex_type = typename base::lockable::mutex_type;

    /// Typedef referencing to resource map which holds handlers groupped by methods
    using resource_map_type = typename session_type::resource_map_type;

    /// Typedef referencing to the method type
    using method_type = typename session_type::method_type;

    /// Typedef referencing to the methods map type
    using method_map_type = typename session_type::method_map_type;

    /// Typedef referencing to the storage type
    using storage_type = typename session_type::storage_type;

    /// Typedef referencing pointer to the methode map type
    using method_map_pointer = std::shared_ptr<method_map_type>;

    /// Typedef referencinf the const pointer to the method map type
    using method_const_map_pointer = std::shared_ptr<const method_map_type>;

    router();

    /// Returns a reference to the `mutex_type`
    /**
     * This function is used to get the mutex for further usage and controlling the critical sections
     *
     * @returns mutex_type
     */
    mutex_type &get_mutex() const;

    /// The method adds handlers and links them within the given path (RegExp) for the `"GET"` method
    /**
     * The method associates a list of handlers and binds to the path for cases, when the respective<br>
     * HTTP method is equal to `"GET"`.
     * The method is instantiated under the following conditions:
     * - `template<class ...OnRequest>` carries the list of executables routines
     * - the methods comply to the signature and may be passed as a parameter for the `sorage` creation
     *
     * ```cpp
     * std::is_invocable_v<OnRequest, const request_type &, context_type &, const std::smatch &>
     * ```
     * 
     * @param path The <tt>std::string</tt> type and refers to RegExp associated within the handlers
     * @param on_request A variadic template of the handlers to be sequentially executed for the given <tt>path</tt>
     * @returns void
     *
     * @note A handler must return either void or bool
     * - in case when the return type is void then the next handler executes right after the current is finished
     * - in case when the return type is the boolean data type and then the execution is based on the following vlaues:
     *   - if return type is `true` then the next handler executes
     *   - if return type is `false` then the complete chain of handlers breaks
     * @note Two cases of handlers declaration:
     * - std::function<bool(const request_type &, context_type &, const std::smatch &)>
     * - std::function<void(const request_type &, context_type &, const std::smatch &)>
     */
    template<class ...OnRequest>
    auto get(const std::string &path, OnRequest &&...on_request)
        -> decltype(storage_type(std::declval<OnRequest>()...), void());

    /// The methods adds handlers and links them within the given path (RegExp) for the `"PUT"` method
    /**
     * @param path The <tt>std::string</tt> type and refers to RegExp associated within the handlers
     * @param on_request A variadic template of the handlers to be sequentially executed for the given <tt>path</tt>
     * @returns void
     * @note For more in details please refere to the get() method description
     */
    template<class ...OnRequest>
    auto put(const std::string &path, OnRequest &&...on_request)
        -> decltype(storage_type(std::declval<OnRequest>()...), void());
    
    /// The methods adds handlers and links them within the given path (RegExp) for the `"POST"` method
    /**
     * @param path The <tt>std::string</tt> type and refers to RegExp associated within the handlers
     * @param on_request A variadic template of the handlers to be sequentially executed for the given <tt>path</tt>
     * @returns void
     * @note For more in details please refere to the get() method description
     */
    template<class ...OnRequest>
    auto post(const std::string &path, OnRequest &&...on_request)
        -> decltype(storage_type(std::declval<OnRequest>()...), void());
    
    /// The methods adds handlers and links them within the given path (RegExp) for the `"DELETE"` method
    /**
     * @param path The <tt>std::string</tt> type and refers to RegExp associated within the handlers
     * @param on_request A variadic template of the handlers to be sequentially executed for the given <tt>path</tt>
     * @returns void
     * @note For more in details please refere to the get() method description
     */
    template<class ...OnRequest>
    auto delete_(const std::string &path, OnRequest &&...on_request)
        -> decltype(storage_type(std::declval<OnRequest>()...), void());

    method_const_map_pointer get_resource_map() const;

private:
    void add_resource(const std::string &path, const method_type &method, storage_type &&storage);

    mutable mutex_type m_mutex;
    method_map_pointer m_method_map;
};

} // namespace beast_router

#include "impl/router.hpp"
